---
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Add labels and selectors to all resources. If the label key already is present
# on the resource, the value will be overridden.
labels: []

# Adds namespace to all resources. Will override the existing namespace if it
# is set on a resource, or add it if it is not set on a resource.
namespace: vikunja

# Patches can be applied to resources that have already been defined. This allows environment-specific
# deviations from the basic setup to be adapted or overwritten in the overlays.
# see https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing
patches: []

resources:
  - resources/pdb.yml
  - resources/postgrsql-db.yml
  - resources/secret.yml
  - resources/service-account.yml
  - resources/service-psql.yml
  - resources/service-vikunja-psql-hl.yml

