---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vikunja-postgresql
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.2.0
    app.kubernetes.io/component: primary
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: vikunja
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
