---
apiVersion: v1
kind: Secret
metadata:
  name: vikunja-postgresql
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.2.0
type: Opaque
data:
  postgres-password: "UThBcGh6cFVQVA=="
  password: "dmlrdW5qYQ=="
