---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-postgresql
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.2.0
    app.kubernetes.io/component: primary
  annotations:
    prometheus.io/path: '/metrics'
    prometheus.io/port: '10254' #todo: change port if needed
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
