---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vikunja-postgresql
  namespace: vikunja
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.2.0
automountServiceAccountToken: false
